// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qukkufgbpvgzcikiykiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1a2t1ZmdicHZnemNpa2l5a2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTE0OTgsImV4cCI6MjA3MTU4NzQ5OH0.wtvNOAMxmW2KHmpVlHHCatO4pVKC0bDogILe7YMJ5uI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});